image: java:latest

before_script:
  - echo nothing

stages:
  - build

build:
  stage: build
  script: 
    - ant clean
    - ant dist
  artifacts:
    name: "cup-binaries-$CI_COMMIT_SHA"
    paths:
    - target/dist/java-cup-11b.jar
    - target/dist/java-cup-11b-runtime.jar

